Feature/implement tutor logic module
herquiloidehele/s-academy pull request #9
Opened 2024-08-04 20:23 UTC by ErcilioMarques

2024-08-04 20:45 UTC, herquiloidehele commented
https://github.com/user-attachments/assets/1a92aa6e-5bca-474e-becb-a4c81db22d3c


The course is not being saved.

2024-08-04 20:48 UTC, herquiloidehele requested changes

2024-08-04 20:48 UTC, herquiloidehele commented on next.config.mjs
> +dotenv.config();
We don't need to use dotenv nextjs already supports clientside env variables
we just need to prefix them with `NEXT_PUBLIC_`

Ex: `NEXT_PUBLIC_FIREBASE_API_KEY`

And then put them in constants as: EXTERNAL_CONFIGS

2024-08-04 21:08 UTC, herquiloidehele requested changes

2024-08-04 21:08 UTC, herquiloidehele commented on src/app/backend/business/course/CourseManager.ts
> +      return JSON.parse(JSON.stringify({ id: lessonId, ...lessonDto }));
same

2024-08-04 21:08 UTC, herquiloidehele commented on src/app/tutor/page.tsx
> +  const setLoggedTutor = useTutorStore.getState?.().setLoggedTutor;
why not put this logic inside the layout or ProtectedRoutes for tutor?

2024-08-04 21:19 UTC, herquiloidehele requested changes

2024-08-04 21:19 UTC, herquiloidehele commented on src/app/tutor/products/courses/components/CourseFormPreview.tsx
> +      toast.success("Erro ao publicar curso");
```suggestion
      toast.error("Erro ao publicar curso");
```

2024-08-04 21:19 UTC, herquiloidehele commented on src/app/tutor/products/courses/components/CourseSchemas.ts
> +// Define um esquema para validação de arquivos (só para tipos de arquivo específicos)
pt

2024-08-04 21:19 UTC, herquiloidehele commented on src/app/tutor/products/courses/components/CoursesCard.tsx
> +              href={`/tutor/products/courses/form/${course.id}`}
Put this routes in constants `APP_ROUTES`

2024-08-04 21:28 UTC, herquiloidehele commented
https://github.com/user-attachments/assets/d4e3a242-f6b5-4134-8515-fd26d2bedd4b


One of this files should be required

2024-08-04 21:59 UTC, ErcilioMarques commented on src/app/backend/business/course/CourseManager.ts
> +      return JSON.parse(JSON.stringify(courses)) as ICourse[];
seems like in client components its fails expecting plain objects

2024-08-04 22:51 UTC, herquiloidehele commented
https://github.com/user-attachments/assets/91ddb0bb-4bfa-4b55-93d3-5ed045aa210f


We shouldn't show the empty state before loading state

2024-08-04 22:57 UTC, herquiloidehele requested changes
![Screenshot 2024-08-04 at 23 55 45](https://github.com/user-attachments/assets/3914af97-154e-4f1d-a755-75f34cef0f9b)

This should be tutor ref

2024-08-04 22:59 UTC, herquiloidehele reviewed
![Screenshot 2024-08-04 at 23 58 43](https://github.com/user-attachments/assets/c8ea6450-0175-4d2a-b09c-b759922e9e74)

Overflow on long descriptions

2024-08-04 23:01 UTC, herquiloidehele requested changes
![Screenshot 2024-08-05 at 00 00 55](https://github.com/user-attachments/assets/95837854-ec52-4b3f-9d20-7c0c246ce92f)

Console errors

2024-08-04 23:04 UTC, herquiloidehele requested changes
https://github.com/user-attachments/assets/59583ec8-904d-4c52-89e3-68908b86cf4e

Missing loading state here

2024-08-04 23:05 UTC, herquiloidehele requested changes
https://github.com/user-attachments/assets/efcdd8d3-116f-4bfb-8754-2f12d5a43ae0

Not possible to upload video in edit course page

2024-08-04 23:10 UTC, herquiloidehele requested changes
https://github.com/user-attachments/assets/04930e64-bb1f-42fd-8139-69b68defaaf4


Try to avoid this multiple re-renders when progress is updated

2024-08-04 23:12 UTC, herquiloidehele requested changes
https://github.com/user-attachments/assets/6572759d-d5ef-47b8-880c-fc45c7044fda

2024-08-04 23:14 UTC, herquiloidehele requested changes
https://github.com/user-attachments/assets/900246e1-3fae-4eba-a287-3546488f0535

Shouldn't be possible to skip steps without filling out the required information.

2024-08-04 23:18 UTC, herquiloidehele requested changes
https://github.com/user-attachments/assets/b5b1e24e-6df7-43b0-8c71-4f4cb7c30d62

The data is not cleared from the store.

2024-08-04 23:34 UTC, herquiloidehele requested changes
https://github.com/user-attachments/assets/c4adf0fe-df2a-4b5f-8a99-1cc197474888

No preview of the uploaded video lesson

2024-08-04 23:35 UTC, herquiloidehele commented
Missing Unpublished button in course details

2024-08-07 20:04 UTC, herquiloidehele requested changes

2024-08-07 20:04 UTC, herquiloidehele commented on src/app/tutor/products/courses/courseStore.ts
> +      console.log(e);
We need to do something with these errors, maybe show an toast to the user.

2024-08-07 20:04 UTC, herquiloidehele commented on src/app/tutor/products/courses/courseStore.ts
> +      console.log(e);
same

2024-08-10 08:28 UTC, herquiloidehele approved these changes

2024-08-10 11:16 UTC, merged